### ISSUE TITLE
Missing NeedsKeyboard Component 

### ISSUE THREAD

**Issue by thibmo** [Facepunch/Rust.Community#25]
It seems that this is missing the NeedsKeyboard component.
Right now when one adds an InputField and selects it to start typing, the game still responds to the keyboard, as in walk around and open other menus.

Maybe this could be solved another way, if so, please tell us! :)

**Comment by Motridox** [comment]
I agree with this. 

Also these things would come in very handy:
Multi line
Text limit

**Comment by thibmo** [comment]
Perhaps also a text hint.
But let's first stick to the basics. :) Fixing the NeedsKeyboard.

**Comment by ElChupos** [comment]
This was implemented and should be released with the May wipe - a3db6f6489247c0b4189d133583b990997ac2dae
