### ISSUE TITLE
[Suggestion] Skin ID Icon should apply once loaded

### ISSUE THREAD

**Issue by dassjosh** [Facepunch/Rust.Community#35]
**Issue:**
When specifying the Skin ID for an icon the skin icon will not be updated in the CUI for the client until the CUI is recreated with the skin ID specified. 

**Suggestion:**
Once the skin icon has been loaded on the client apply it to the CUI icon so the CUI doesn't need to be destroyed and recreated to display the recently loaded skin icon.

**Comment by ElChupos** [comment]
This should be fixed in https://github.com/Facepunch/Rust.Community/commit/cc2d3bb30c63722b06dfe7393d88905e4ef37e99
